services:
  multi-login-write:
    container_name: multi-login-write
    image: 'postgres:alpine'
    environment:
      POSTGRES_DB: multi-login-write
      POSTGRES_USER: secret
      POSTGRES_PASSWORD: secret
      PGDATA: /data/multi-login-write
    volumes:
      - multi-login-write:/data/multi-login-write
    ports:
      - '5432:5432'
    networks:
      - postgres
    restart: unless-stopped

  multi-login-read:
    container_name: multi-login-read
    image: 'postgres:alpine'
    environment:
      POSTGRES_DB: multi-login-read
      POSTGRES_USER: secret
      POSTGRES_PASSWORD: secret
      PGDATA: /data/multi-login-read
    volumes:
      - multi-login-read:/data/multi-login-read
    ports:
      - '5433:5432'
    networks:
      - postgres
    restart: unless-stopped


  adminer:
    container_name: adminer
    image: adminer
    restart: unless-stopped
    volumes:
      - adminer:/var/lib/adminer
    ports:
      - '8888:8080'
    networks:
      - postgres

networks:
  postgres:
    driver: bridge

volumes:
  multi-login-write:
  multi-login-read:
  adminer: