global:
  scrape_interval: 15s
  evaluation_interval: 15s
scrape_configs:
  - job_name: 'prometheus'
    static_configs:
      - targets: ['localhost:9090', 'node-exporter:9100' ]

  - job_name: 'postgres-exporter'
    static_configs:
      - targets: ['host.docker.internal:9187', 'host.docker.internal:9188']

  - job_name: 'multi-login'
    scrape_interval: 5s
    metrics_path: /observe/prometheus
    static_configs:
      - targets: ['host.docker.internal:8080']
        labels:
          application: 'Multi Login App'
    basic_auth:
      username: 'prometheus'
      password: 'prometheus'

alerting:
  alertmanagers:
    - scheme: http
      static_configs:
        - targets: ['alert-manager:9093']

rule_files:
  - alerting-rules.yml