global:
  smtp_smarthost: 'mail-pit:1025'
  smtp_from: '"Grafana Alerts" <alertmanager@vicynet.dev>' # The sender's name and email
  smtp_hello: 'vicynet.dev'
  smtp_require_tls: false

route:
  group_by: ['alertname']
  group_wait: 30s
  group_interval: 5m
  repeat_interval: 1h
  receiver: 'email'
#  receivers:
#    - 'email'
##    - 'slack'

receivers:
  - name: 'email'
    email_configs:
      - to: 'log@vicynet.dev'
        send_resolved: true

#  - name: 'slack'
#    slack_configs:
#      - api_url: 'https://hooks.slack.com/services/YOUR/SLACK/WEBHOOK'
#        channel: '#alerts'
#        send_resolved: true
